### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './cache/RandStates_CUB_s1_q15_w5'

### ISSUE THREAD

**Issue by Henkwu** [ShuoYang-1998/Few_Shot_Distribution_Calibration#11]
This is good work. There is a mistake when I run this code. How to solve this problem?

_FileNotFoundError: [Errno 2] No such file or directory: './cache/RandStates_CUB_s1_q15_w5'_

**Comment by Henkwu** [comment]
Guaranteed number of items per class: 48

Total of 50 classes, 48 elements each, with dimension 640

./cache/RandStates_CUB_s1_q15_w5 does not exist, regenerating it...
./cache/RandStates_CUB_s1_q15_w5
Traceback (most recent call last):
  File "evaluate_DC.py", line 39, in <module>
    FSLTask.setRandomStates(cfg)
  File "/media/space/WH/WH/Few-Shot/Few_Shot_Distribution_Calibration/FSLTask.py", line 119, in setRandomStates
    torch.save(_randStates, rsFile)
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.6/site-packages/torch/serialization.py", line 361, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './cache/RandStates_CUB_s1_q15_w5'

**Comment by Caiyou1001** [comment]
现遇相同错误，怎么解决的

**Comment by mrzhu666** [comment]
create folder "cache"
