### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './cache\\RandStates_miniImagenet_s1_q15_w5'

### ISSUE THREAD

**Issue by c1a1o1** [ShuoYang-1998/Few_Shot_Distribution_Calibration#20]
F:\ProgramData\Anaconda3\python.exe "F:/work/paper 2021/translation/Few_Shot_Distribution_Calibration-master/evaluate_DC.py"
Guaranteed number of items per class: 600

Total of 20 classes, 600 elements each, with dimension 640

./cache\RandStates_miniImagenet_s1_q15_w5 does not exist, regenerating it...
Traceback (most recent call last):
  File "F:/work/paper 2021/translation/Few_Shot_Distribution_Calibration-master/evaluate_DC.py", line 37, in <module>
    FSLTask.setRandomStates(cfg)
  File "F:\work\paper 2021\translation\Few_Shot_Distribution_Calibration-master\FSLTask.py", line 118, in setRandomStates
    torch.save(_randStates, rsFile)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 369, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './cache\\RandStates_miniImagenet_s1_q15_w5'

**Comment by c1a1o1** [comment]
create folder "cache"
